version: '2'
services:
  app:
    build: .
    image: cheat.sh
    container_name: chtsh
    depends_on:
      - redis
    environment:
      - CHEATSH_CACHE_REDIS_HOST=redis
    ports:
      - "8002:8002"
  redis:
    image: redis:4-alpine
    volumes:
      - redis_data:/data
volumes:
  redis_data:
